### PR TITLE
GUI improvements for mid-v1.3

### PR DESCRIPTION
**Pull request by nattanyz**
refactoring of GUI-related classes :)

### CODE REVIEW

**Comment by nattanyz** [comment]
will merge once i fix checkstyle! :)

**Comment by huiminlim** [comment]
@nattanyz Any issue with this PR?

**Comment by nattanyz** [comment]
need to fix checkstyle! will do so when i’m home :)

**Comment by huiminlim** [comment]
alright, let us know if need help

**Pull request merged**
